Repository apility/netflex-sdk, pull requests merged in 2019-06, with the labels that each got.

#42 Entry retrieval issues
  src/functions/common/functions_directories.php
  src/model/Structure.php
  tests/TestSuites/Common/function_directories/__snapshots__/Common_GetDirectoryEntryTest__testCanOverrideRevision__2.json
  tests/TestSuites/Common/function_directories/__snapshots__/Common_GetDirectoryEntryTest__testCanOverrideRevision__3.json
  tests/TestSuites/Common/function_directories/__snapshots__/Common_GetEntryTest__testCanOverrideRevision__2.json
  tests/TestSuites/Common/function_directories/__snapshots__/Common_GetEntryTest__testCanOverrideRevision__3.json
  tests/TestSuites/Common/function_directories/common.get_directory_entry.test.php
  tests/TestSuites/Common/function_directories/common.get_entry.test.php
  tests/TestSuites/Common/function_directories/common.get_entry_content_list.test.php
  tests/TestSuites/Common/function_directories/common.get_entry_variants.test.php
Labels: bug

#45 Test suite for CaptchaV2
  phpunit.xml
  src/Netflex/Site/Support/CaptchaV2.php
  tests/TestSuites/CaptchaV2/CaptchaV2.checkBox.test.php
  tests/TestSuites/CaptchaV2/CaptchaV2.isValid.test.php
  tests/TestSuites/CaptchaV2/CaptchaV2.scriptTag.test.php
  tests/TestSuites/CaptchaV2/__snapshots__/CaptchaV2_CheckBoxTest__testMatchesSnapshot__1.txt
  tests/TestSuites/CaptchaV2/__snapshots__/CaptchaV2_ScriptTagTest__testMatchesSnapshots__1.txt
  tests/TestSuites/CaptchaV2/__snapshots__/CaptchaV2_ScriptTagTest__testMatchesSnapshots__2.txt
Labels: enhancement

#46 Release/1.0.10
  phpunit.xml
  src/Netflex/Site/Support/CaptchaV2.php
  tests/TestSuites/CaptchaV2/CaptchaV2.checkBox.test.php
  tests/TestSuites/CaptchaV2/CaptchaV2.isValid.test.php
  tests/TestSuites/CaptchaV2/CaptchaV2.scriptTag.test.php
  tests/TestSuites/CaptchaV2/__snapshots__/CaptchaV2_CheckBoxTest__testMatchesSnapshot__1.txt
  tests/TestSuites/CaptchaV2/__snapshots__/CaptchaV2_ScriptTagTest__testMatchesSnapshots__1.txt
  tests/TestSuites/CaptchaV2/__snapshots__/CaptchaV2_ScriptTagTest__testMatchesSnapshots__2.txt
Labels: enhancement

#49 Refactor Console handler
  src/NF.php
  src/Netflex/Site/Console.php
  tests/mocks/NF.php
  tests/mocks/PHPConsole.php
Labels: enhancement

#48 Add a Cache “get or set” function using callbacks
  src/Netflex/Site/Cache.php
Labels: enhancement

#52 Hotfix: Optimize structure metadata fetching
  src/pagefinder/preview_entry.php
Labels: hotfix

#55 v1.0.13
  src/functions/common/functions_directories.php
  src/pagefinder/preview_entry.php
  tests/TestSuites/Common/function_directories/__snapshots__/Common_GetDirectoryEntryTest__testCanOverrideRevision__1.json
  tests/TestSuites/Common/function_directories/__snapshots__/Common_GetDirectoryEntryTest__testCanOverrideRevision__2.json
  tests/TestSuites/Common/function_directories/__snapshots__/Common_GetEntryTest__testCanOverrideRevision__1.json
  tests/TestSuites/Common/function_directories/__snapshots__/Common_GetEntryTest__testCanOverrideRevision__2.json
Labels: enhancement
